name: Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  run-tests-group-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests - Group 1
        run: npx cypress run --spec "cypress/e2e/Bank/test.cy.js" --reporter mocha-allure-reporter --reporter-options targetDir=cypress/allure-results/group1

      - name: Upload Group 1 report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-group-1
          path: cypress/allure-results/group1

  run-tests-group-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests - Group 2
        run: npx cypress run --spec "cypress/e2e/Bank/test2.cy.js" --reporter mocha-allure-reporter --reporter-options targetDir=cypress/allure-results/group2

      - name: Upload Group 2 report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-group-2
          path: cypress/allure-results/group2

  merge-and-generate-allure-report:
    runs-on: ubuntu-latest
    needs: [run-tests-group-1, run-tests-group-2]
    if: ${{ always() }} # Run this step regardless of the test group status
    steps:
      - name: Download report artifacts - Group 1
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: allure-report-group-1
          path: cypress/allure-results/group1

      - name: Download report artifacts - Group 2
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: allure-report-group-2
          path: cypress/allure-results/group2

      - name: Merge Allure Results
        run: |
          mkdir -p cypress/allure-results/merged
          cp -r cypress/allure-results/group1/* cypress/allure-results/merged/
          cp -r cypress/allure-results/group2/* cypress/allure-results/merged/

      - name: Install Allure CLI
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jre wget
          wget https://github.com/allure-framework/allure2/releases/download/2.17.3/allure-2.17.3.tgz
          tar -zxvf allure-2.17.3.tgz
          sudo mv allure-2.17.3 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate Allure HTML Report
        run: |
          allure generate cypress/allure-results/merged --clean -o cypress/allure-report

      - name: Upload Allure HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-report
          path: cypress/allure-report
