name: Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

  run-tests-group-1:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore cached node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Run Cypress tests - Group 1
        run: npx cypress run --spec "cypress/e2e/Bank/test.cy.js"

      - name: Upload Group 1 report
        uses: actions/upload-artifact@v3
        with:
          name: report-group-1
          path: cypress/reports/*.json

  run-tests-group-2:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore cached node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Run Cypress tests - Group 2
        run: npx cypress run --spec "cypress/e2e/Bank/test2.cy.js"

      - name: Upload Group 2 report
        uses: actions/upload-artifact@v3
        with:
          name: report-group-2
          path: cypress/reports/*.json

  merge-reports:
    runs-on: ubuntu-latest
    needs: [run-tests-group-1, run-tests-group-2]
    steps:
      - name: Download Group 1 Report Artifacts
        uses: actions/download-artifact@v3
        with:
          name: report-group-1
          path: cypress/reports/group1

      - name: Download Group 2 Report Artifacts
        uses: actions/download-artifact@v3
        with:
          name: report-group-2
          path: cypress/reports/group2

      - name: Install mochawesome-merge
        run: npm install -g mochawesome-merge

      - name: Merge Reports
        run: |
          mochawesome-merge cypress/reports/group1/*.json cypress/reports/group2/*.json > cypress/reports/merged-report.json

      - name: Upload Merged Report
        uses: actions/upload-artifact@v3
        with:
          name: cypress-merged-report
          path: cypress/reports/merged-report.json
