name: Cypress Tests with Allure Reports

on:
  push:
    branches:
      - master

jobs:
  run-tests-group-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Install Allure Reporter and Command Line (CI only)
        run: |
          npm install --save-dev @shelex/cypress-allure-plugin allure-commandline

      - name: Run Cypress tests - Group 1 with Allure Reporter
        run: npx cypress run --spec "cypress/e2e/Bank/test.cy.js" --reporter @shelex/cypress-allure-plugin --reporter-options allureResultsPath=cypress/allure-results

      - name: Upload Group 1 report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-group-1
          path: cypress/allure-results/*.json

  run-tests-group-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Install Allure Reporter and Command Line (CI only)
        run: |
          npm install --save-dev @shelex/cypress-allure-plugin allure-commandline

      - name: Run Cypress tests - Group 2 with Allure Reporter
        run: npx cypress run --spec "cypress/e2e/Bank/test2.cy.js" --reporter @shelex/cypress-allure-plugin --reporter-options allureResultsPath=cypress/allure-results

      - name: Upload Group 2 report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-group-2
          path: cypress/allure-results/*.json

  merge-reports:
    runs-on: ubuntu-latest
    needs: [run-tests-group-1, run-tests-group-2]
    if: ${{ always() }}
    steps:
      - name: Download report artifacts - Group 1
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: report-group-1
          path: cypress/allure-results

      - name: Download report artifacts - Group 2
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: report-group-2
          path: cypress/allure-results

      - name: List files before merging
        run: ls -al cypress/allure-results/

      - name: Clear previous reports
        run: rm -f cypress/allure-results/*.json

      - name: Merge Allure Results
        run: |
          allure generate cypress/allure-results --clean -o cypress/allure-report

      - name: Debug Allure report
        run: ls -al cypress/allure-report/

      - name: Upload Merged Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: cypress/allure-report
