name: Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_file: 
          - "cypress/e2e/Bank/test.cy.js"
          - "cypress/e2e/Bank/test2.cy.js"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: cypress-${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: |
          TEST_NAME=$(basename ${{ matrix.test_file }} .js)
          npx cypress run --spec "${{ matrix.test_file }}" --reporter mochawesome --reporter-options "reportDir=cypress/reports,reportFilename=mochawesome-${TEST_NAME}"

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.test_file }}
          path: cypress/reports/*.json

  merge-reports:
    runs-on: ubuntu-latest
    needs: run-tests
    if: ${{ always() }}
    steps:
      - name: Download report artifacts
        uses: actions/download-artifact@v4
        with:
          name: report-${{ matrix.test_file }}
          path: cypress/reports

      - name: Install mochawesome-merge
        run: npm install -g mochawesome-merge

      - name: Merge Reports
        run: |
          mochawesome-merge cypress/reports/*.json > cypress/reports/merged-report.json

      - name: Upload Merged Report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-merged-report
          path: cypress/reports/merged-report.json
