name: Cypress Tests with Allure Report

on:
  push:
    branches:
      - master

jobs:
  run-tests-group-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests - Group 1
        run: npx cypress run --spec "cypress/e2e/Bank/test.cy.js" --reporter mocha-allure-reporter --reporter-options allureResultsPath=cypress/allure-results

      - name: Upload Group 1 Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-group-1
          path: cypress/allure-results

  run-tests-group-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests - Group 2
        run: npx cypress run --spec "cypress/e2e/Bank/test2.cy.js" --reporter mocha-allure-reporter --reporter-options allureResultsPath=cypress/allure-results

      - name: Upload Group 2 Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-group-2
          path: cypress/allure-results

  generate-allure-report:
    runs-on: ubuntu-latest
    needs: [run-tests-group-1, run-tests-group-2]
    if: ${{ always() }}
    steps:
      - name: Download Allure results - Group 1
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: allure-results-group-1
          path: cypress/allure-results

      - name: Download Allure results - Group 2
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: allure-results-group-2
          path: cypress/allure-results

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Generate Allure HTML Report
        run: |
          allure generate cypress/allure-results --clean -o allure-report

      - name: Upload Allure HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-report
          path: allure-report
