name: Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  run-tests-group-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests - Group 1
        run: npx cypress run --spec "cypress/e2e/Bank/test.cy.js"

      - name: Upload Group 1 report
        uses: actions/upload-artifact@v2
        with:
          name: report-group-1
          path: cypress/reports/*.json

  run-tests-group-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests - Group 2
        run: npx cypress run --spec "cypress/e2e/Bank/test2.cy.js"

      - name: Upload Group 2 report
        uses: actions/upload-artifact@v2
        with:
          name: report-group-2
          path: cypress/reports/*.json

  merge-reports:
    runs-on: ubuntu-latest
    needs: [run-tests-group-1, run-tests-group-2] # Run this step after both test groups
    steps:
      - name: Download report artifacts
        uses: actions/download-artifact@v2
        with:
          name: report-group-1
          path: cypress/reports

      - name: Download second report artifacts
        uses: actions/download-artifact@v2
        with:
          name: report-group-2
          path: cypress/reports

      - name: Install mochawesome-merge
        run: npm install -g mochawesome-merge

      - name: Merge Reports
        run: |
          mochawesome-merge cypress/reports/*.json > cypress/reports/merged-report.json

      - name: Upload Merged Report
        uses: actions/upload-artifact@v2
        with:
          name: cypress-merged-report
          path: cypress/reports/merged-report.json